export default [
     {
          id: 'asdfASFASas',
          title: 'Buenos Aires Bar Oculto 21hs',
          date: '5-12-23',
          mounth: 'enero',
          description:
               'Hola chicos, nos encontraremos el día 20/10/2022 por la noche para celebrar año nuevo',
          link: 'https://goo.gl/maps/dGWai2KJmp24dp1F6',
          author: {
               idUser: 'asdas564',
               name: 'Agustin Ojeda',
          },
          people: [
               { idUser: 'asdaasddsd', name: 'Juani' },
               { idUser: 'asdasd', name: 'Agus' },
               { idUser: 'asdasasd', name: 'Uli' },
               { idUser: 'asdaasdsd', name: 'Mary' },
               { idUser: 'asdaasdsdd', name: 'Raul' },
               { idUser: 'asdaFsd', name: 'Juan' },
               { idUser: 'asdaASsqd', name: 'Pablo' },
          ],
          comments: [
               {
                    idComment: 'asdasdasd',
                    idUser: 'asdasdcasq1',
                    name: 'Juan',
                    comment: 'Buenisimo tilin',
               },
               {
                    idComment: 'asdasdadahsd',
                    idUser: 'asdasdcasq1',
                    name: 'Uli',
                    comment: 'Habrá enanos? Sino no voy',
               },
               {
                    idComment: 'asdgasdasasd',
                    idUser: 'asdasdcasq1',
                    name: 'Chino',
                    comment: 'okaa',
               },
               {
                    idComment: 'asdasdashasd',
                    idUser: 'asdasdcasq1',
                    name: 'Rebe',
                    comment: 'okii',
               },
               {
                    idComment: 'asdasdahsasd',
                    idUser: 'asdasdcasq1',
                    name: 'Mary',
                    comment: 'dalee, nos vemos',
               },
          ],
          favorites: true,
     },
     {
          id: 'asdasasfa',
          title: 'Buenos Aires Bar Oculto 21hs',
          date: '5',
          mounth: 'enero',
          description:
               'Hola chicos, nos encontraremos el día 20/10/2022 por la noche para celebrar año nuevo',
          link: 'https://goo.gl/maps/dGWai2KJmp24dp1F6',
          author: {
               idUser: 'asdas564',
               name: 'Agustin Ojeda',
          },
          people: [
               { idUser: 'asdaasddsd', name: 'Juani' },
               { idUser: 'asdasd', name: 'Agus' },
               { idUser: 'asdasasd', name: 'Uli' },
               { idUser: 'asdaasdsd', name: 'Mary' },
               { idUser: 'asdaasdsdd', name: 'Raul' },
               { idUser: 'asdaFsd', name: 'Juan' },
               { idUser: 'asdaASsqd', name: 'Pablo' },
          ],
          comments: [
               {
                    idComment: 'asdasdasd',
                    idUser: 'asdasdcasq1',
                    name: 'Juan',
                    comment: 'Buenisimo tilin',
               },
               {
                    idComment: 'asdasdadahsd',
                    idUser: 'asdasdcasq1',
                    name: 'Uli',
                    comment: 'Habrá enanos? Sino no voy',
               },
               {
                    idComment: 'asdgasdasasd',
                    idUser: 'asdasdcasq1',
                    name: 'Chino',
                    comment: 'okaa',
               },
               {
                    idComment: 'asdasdashasd',
                    idUser: 'asdasdcasq1',
                    name: 'Rebe',
                    comment: 'okii',
               },
               {
                    idComment: 'asdasdahsasd',
                    idUser: 'asdasdcasq1',
                    name: 'Mary',
                    comment: 'dalee, nos vemos',
               },
          ],
          favorites: true,
     },
     {
          id: 'asdasdfgsags',
          title: 'Buenos Aires Bar Oculto 21hs',
          date: '5',
          mounth: 'enero',
          description:
               'Hola chicos, nos encontraremos el día 20/10/2022 por la noche para celebrar año nuevo',
          link: 'https://goo.gl/maps/dGWai2KJmp24dp1F6',
          author: {
               idUser: 'asdas564',
               name: 'Agustin Ojeda',
          },
          people: [
               { idUser: 'asdaasddsd', name: 'Juani' },
               { idUser: 'asdasd', name: 'Agus' },
               { idUser: 'asdasasd', name: 'Uli' },
               { idUser: 'asdaasdsd', name: 'Mary' },
               { idUser: 'asdaasdsdd', name: 'Raul' },
               { idUser: 'asdaFsd', name: 'Juan' },
               { idUser: 'asdaASsqd', name: 'Pablo' },
          ],
          comments: [
               {
                    idComment: 'asdasdasd',
                    idUser: 'asdasdcasq1',
                    name: 'Juan',
                    comment: 'Buenisimo tilin',
               },
               {
                    idComment: 'asdasdadahsd',
                    idUser: 'asdasdcasq1',
                    name: 'Uli',
                    comment: 'Habrá enanos? Sino no voy',
               },
               {
                    idComment: 'asdgasdasasd',
                    idUser: 'asdasdcasq1',
                    name: 'Chino',
                    comment: 'okaa',
               },
               {
                    idComment: 'asdasdashasd',
                    idUser: 'asdasdcasq1',
                    name: 'Rebe',
                    comment: 'okii',
               },
               {
                    idComment: 'asdasdahsasd',
                    idUser: 'asdasdcasq1',
                    name: 'Mary',
                    comment: 'dalee, nos vemos',
               },
          ],
          favorites: true,
     },
     {
          id: 'asdafsaass',
          title: 'Buenos Aires Bar Oculto 21hs',
          date: '5',
          mounth: 'enero',
          description:
               'Hola chicos, nos encontraremos el día 20/10/2022 por la noche para celebrar año nuevo',
          link: 'https://goo.gl/maps/dGWai2KJmp24dp1F6',
          author: {
               idUser: 'asdas564',
               name: 'Agustin Ojeda',
          },
          people: [
               { idUser: 'asdaasddsd', name: 'Juani' },
               { idUser: 'asdasd', name: 'Agus' },
               { idUser: 'asdasasd', name: 'Uli' },
               { idUser: 'asdaasdsd', name: 'Mary' },
               { idUser: 'asdaasdsdd', name: 'Raul' },
               { idUser: 'asdaFsd', name: 'Juan' },
               { idUser: 'asdaASsqd', name: 'Pablo' },
          ],
          comments: [
               {
                    idComment: 'asdasdasd',
                    idUser: 'asdasdcasq1',
                    name: 'Juan',
                    comment: 'Buenisimo tilin',
               },
               {
                    idComment: 'asdasdadahsd',
                    idUser: 'asdasdcasq1',
                    name: 'Uli',
                    comment: 'Habrá enanos? Sino no voy',
               },
               {
                    idComment: 'asdgasdasasd',
                    idUser: 'asdasdcasq1',
                    name: 'Chino',
                    comment: 'okaa',
               },
               {
                    idComment: 'asdasdashasd',
                    idUser: 'asdasdcasq1',
                    name: 'Rebe',
                    comment: 'okii',
               },
               {
                    idComment: 'asdasdahsasd',
                    idUser: 'asdasdcasq1',
                    name: 'Mary',
                    comment: 'dalee, nos vemos',
               },
          ],
          favorites: true,
     },
     {
          id: 'asdasdasd as',
          title: 'Buenos Aires Bar Oculto 21hs',
          date: '5',
          mounth: 'enero',
          description:
               'Hola chicos, nos encontraremos el día 20/10/2022 por la noche para celebrar año nuevo',
          link: 'https://goo.gl/maps/dGWai2KJmp24dp1F6',
          author: {
               idUser: 'asdas564',
               name: 'Agustin Ojeda',
          },
          people: [
               { idUser: 'asdaasddsd', name: 'Juani' },
               { idUser: 'asdasd', name: 'Agus' },
               { idUser: 'asdasasd', name: 'Uli' },
               { idUser: 'asdaasdsd', name: 'Mary' },
               { idUser: 'asdaasdsdd', name: 'Raul' },
               { idUser: 'asdaFsd', name: 'Juan' },
               { idUser: 'asdaASsqd', name: 'Pablo' },
          ],
          comments: [
               {
                    idComment: 'asdasdasd',
                    idUser: 'asdasdcasq1',
                    name: 'Juan',
                    comment: 'Buenisimo tilin',
               },
               {
                    idComment: 'asdasdadahsd',
                    idUser: 'asdasdcasq1',
                    name: 'Uli',
                    comment: 'Habrá enanos? Sino no voy',
               },
               {
                    idComment: 'asdgasdasasd',
                    idUser: 'asdasdcasq1',
                    name: 'Chino',
                    comment: 'okaa',
               },
               {
                    idComment: 'asdasdashasd',
                    idUser: 'asdasdcasq1',
                    name: 'Rebe',
                    comment: 'okii',
               },
               {
                    idComment: 'asdasdahsasd',
                    idUser: 'asdasdcasq1',
                    name: 'Mary',
                    comment: 'dalee, nos vemos',
               },
          ],
          favorites: true,
     },
     {
          id: 'asdasdasas',
          title: 'Buenos Aires Bar Oculto 21hs',
          date: '5',
          mounth: 'enero',
          description:
               'Hola chicos, nos encontraremos el día 20/10/2022 por la noche para celebrar año nuevo',
          link: 'https://goo.gl/maps/dGWai2KJmp24dp1F6',
          author: {
               idUser: 'asdas564',
               name: 'Agustin Ojeda',
          },
          people: [
               { idUser: 'asdaasddsd', name: 'Juani' },
               { idUser: 'asdasd', name: 'Agus' },
               { idUser: 'asdasasd', name: 'Uli' },
               { idUser: 'asdaasdsd', name: 'Mary' },
               { idUser: 'asdaasdsdd', name: 'Raul' },
               { idUser: 'asdaFsd', name: 'Juan' },
               { idUser: 'asdaASsqd', name: 'Pablo' },
          ],
          comments: [
               {
                    idComment: 'asdasdasd',
                    idUser: 'asdasdcasq1',
                    name: 'Juan',
                    comment: 'Buenisimo tilin',
               },
               {
                    idComment: 'asdasdadahsd',
                    idUser: 'asdasdcasq1',
                    name: 'Uli',
                    comment: 'Habrá enanos? Sino no voy',
               },
               {
                    idComment: 'asdgasdasasd',
                    idUser: 'asdasdcasq1',
                    name: 'Chino',
                    comment: 'okaa',
               },
               {
                    idComment: 'asdasdashasd',
                    idUser: 'asdasdcasq1',
                    name: 'Rebe',
                    comment: 'okii',
               },
               {
                    idComment: 'asdasdahsasd',
                    idUser: 'asdasdcasq1',
                    name: 'Mary',
                    comment: 'dalee, nos vemos',
               },
          ],
          favorites: true,
     },
     {
          id: 'asasdasdas',
          title: 'Buenos Aires Bar Oculto 21hs',
          date: '5',
          mounth: 'enero',
          description:
               'Hola chicos, nos encontraremos el día 20/10/2022 por la noche para celebrar año nuevo',
          link: 'https://goo.gl/maps/dGWai2KJmp24dp1F6',
          author: {
               idUser: 'asdas564',
               name: 'Agustin Ojeda',
          },
          people: [
               { idUser: 'asdaasddsd', name: 'Juani' },
               { idUser: 'asdasd', name: 'Agus' },
               { idUser: 'asdasasd', name: 'Uli' },
               { idUser: 'asdaasdsd', name: 'Mary' },
               { idUser: 'asdaasdsdd', name: 'Raul' },
               { idUser: 'asdaFsd', name: 'Juan' },
               { idUser: 'asdaASsqd', name: 'Pablo' },
          ],
          comments: [
               {
                    idComment: 'asdasdasd',
                    idUser: 'asdasdcasq1',
                    name: 'Juan',
                    comment: 'Buenisimo tilin',
               },
               {
                    idComment: 'asdasdadahsd',
                    idUser: 'asdasdcasq1',
                    name: 'Uli',
                    comment: 'Habrá enanos? Sino no voy',
               },
               {
                    idComment: 'asdgasdasasd',
                    idUser: 'asdasdcasq1',
                    name: 'Chino',
                    comment: 'okaa',
               },
               {
                    idComment: 'asdasdashasd',
                    idUser: 'asdasdcasq1',
                    name: 'Rebe',
                    comment: 'okii',
               },
               {
                    idComment: 'asdasdahsasd',
                    idUser: 'asdasdcasq1',
                    name: 'Mary',
                    comment: 'dalee, nos vemos',
               },
          ],
          favorites: true,
     },
];
